异常处理
try:
    a = 1/0
except Exception as e:
    print(e) # division by zero
finally:
    print("finally")


with的使用
